### ISSUE TITLE
 Add script to allow IP address to be assigned 

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift-b2d-iso#59]
### Updated
The issue is with how the B2D image handles the hyper-v data exchange module, which is part of the kernel. Since b2d uses a module, the values are not available in time to provide an IP address before DHCP has assigned one. The module seems to read the pool and clears the values? At least, while the WMI call as used in gbraad/go-hvkvp is received and confirmed, the value is not available, even after the module is loaded. It is therefore needed to resend the message several times... and there is no indication if the call actually succeeds.

### Todo
  * [x] create `minishift-staticip.sh` script
    * if IpAddress is available
    * else leave DHCP setting
    * [x] use given netmask
    * [x] use given nameserver
    * [x] use given gateway 
  * [x] add executable to ISO image
    * [x] first use: https://github.com/gbraad/go-hvkvp/releases/tag/0.1
    * [x] use latest from https://github.com/gbraad/go-hvkvp/issues/3

Refer: https://github.com/minishift/minishift/issues/1316

**Comment by gbraad** [comment]
Extension is available at: http://files.gbraad.nl/hvkvp/

**Comment by gbraad** [comment]
Testing with #61

**Comment by gbraad** [comment]
Want to be able to force an IP address using a file, such as `network` and `network-scripts` works. In our case, the file will have to reside on `/mnt/sda1/etc/???`

**Comment by gbraad** [comment]
blocker: pool gets cleared on start boot2docker/boot2docker#1274
workaround does not provide a good enough experience (needs to disable IPv6)
